### ISSUE TITLE
early stop?

### ISSUE THREAD

**Issue by bscully27** [HDI-Project/BTB#106]
Can an early stop be added given score does not increase by X after Y tries?

Not loving "for i in range(100):"

Now that i'm writing this, I can just add a break line for a quick fix..

**Comment by micahjsmith** [comment]
BTB won't do all this work for you. The tuner just proposes new hyperparameters to you and you respond with how they did. The tuner itself will never try to determine a stopping criterion. 

If you want to implement logic like above in your own application, it is pretty easy, as you note.
``` python
from btb.tuning import GP
from queue import deque
tuner = GP(...)
last_scores = deque(maxlen=Y)
while True:
    parameters = tuner.propose()
    score = score_model_with_parameters(parameters)  # or similar
    if last_scores and score - last_scores[0] < X:
        break
    tuner.add(parameters, score)
    last_scores.append(score)
```
alternately you can access the tuner's store of scores directly
``` python
while True:
    # ...
    if score - tuner.y[-Y] < X:
        break
```

**Comment by csala** [comment]
@micahjsmith Should this be closed?
