### ISSUE TITLE
Throw away typed distributions types

### ISSUE THREAD

**Issue by KOLANICH** [HDI-Project/BTB#108]
IMHO:

`StringCatHyperParameter`, `IntCatHyperParameter`, `FloatCatHyperParameter` are not needed. Just `CatHyperParameter`.

```ParamTypes``` is also unneeded. String is a scalar, scalar is a degenerate cathegory. Distributions should be decoupled from types, for distributions `scipy.stats` should be used, and for types ... types themselves.

You may want to look at [my implementation](https://gitlab.com/KOLANICH/UniOpt.py/blob/master/UniOpt/core/Spec.py)

**Comment by micahjsmith** [comment]
Thanks for your feedback!

**Comment by KOLANICH** [comment]
So, are you going to implement it or prefer leave everything as it is?

**Comment by csala** [comment]
Hi @KOLANICH hyperparameters will soon undergo a design review and refactoring in order to support several of the new requirements, like #80, #111, #112 and #113 

So we take notes of your suggestion as well, but this stays closed for now, as it won't be implemented as something on its own.

**Comment by KOLANICH** [comment]
Thank you for the clarification.
