### ISSUE TITLE
Adapt to the latest cookiecutter changes

### ISSUE THREAD

**Issue by csala** [HDI-Project/BTB#110]
The DAI-Lab cookiecutter template was updated since it was used here, and some interesting things were added, like the new Makefile, the new tox configuration, etc.

We should review these changes replicate the ones that are missing here.

**Comment by micahjsmith** [comment]
See also https://github.com/HDI-Project/ballet/issues/22

We want an easy way to incorporate changes from the cookiecutter.

**Comment by pvk-developer** [comment]
This is already fixed after #131 .
