### ISSUE TITLE
Support open ranges

### ISSUE THREAD

**Issue by csala** [HDI-Project/BTB#113]
Sometimes there are hyperparameters that are defined within an open or semi-open range, like `[0, 1)`.

These cases are not natively supported right now, and the only option for the user is to manually add or substract an epsilon to the range edge.

For example, the `[0, 1)` case above could be covered like this:

```
HyperParameter(ParamTypes.INT, [0, 1 - 1e-12])
```

Should we figure out a way to support this natively in BTB?

One option would be having `upper_open/lower_open` or `upper_included/lower_included` flags:

```
HyperParameter(ParamTypes.INT, [0, 1], upper_open=True)   # this means [0, 1)
```

**Comment by pvk-developer** [comment]
This is solved after the #132  implementation. Now we work with
* include_min (bool): Wheither or not to include the minimum value in the search space.
* include_max (bool): Wheither or not to include the maximum value in the search space.
