### ISSUE TITLE
Tuner repr not helpful

### ISSUE THREAD

**Issue by micahjsmith** [HDI-Project/BTB#120]
* BTB version: 0.2.5-dev

### Description

The repr of Tuner objects is not helpful. Hopefully it should show information about the tunables.

Example:
```
In [1]: from btb import HyperParameter

In [2]: from btb.tuning import GP

In [3]: tunables = [('a', HyperParameter('int', [0, 10]))]

In [4]: tuner = GP(tunables)

In [5]: tuner
Out[5]: <btb.tuning.gp.GP at 0x1182940f0>
```

Expected output something like:
```
GP(tunables=[('a', IntHyperParameter(min=0, max=10))])
```

**Comment by csala** [comment]
Consider this: https://github.com/HDI-Project/BTB/issues/121#issuecomment-466442257

In this case, if the HyperParameter `__repr__` is right and it is used within the Tuner `__repr__`, the output suggested here seems totally right.

**Comment by pvk-developer** [comment]
Considering this: https://github.com/HDI-Project/BTB/issues/121#issuecomment-561096389 
I will be implementing this as part of #141
