### ISSUE TITLE
HyperParameter repr not helpful

### ISSUE THREAD

**Issue by micahjsmith** [HDI-Project/BTB#121]
* BTB version: 0.2.5-dev

### Description

The repr of HyperParameter objects is not helpful. Hopefully it should show information about the hyperparameter, such as what type it is and any parameters of that type.

Example
```
In [1]: from btb import HyperParameter

In [2]: HyperParameter('int', [0, 10])
Out[2]: <btb.hyper_parameter.IntHyperParameter at 0x109671fd0>

In [3]: HyperParameter('string', ['a', 'b', 'c'])
Out[3]: <btb.hyper_parameter.StringCatHyperParameter at 0x1096d11d0>

In [4]: HyperParameter('float_exp', [1e1, 1e10])
Out[4]: <btb.hyper_parameter.FloatExpHyperParameter at 0x109722400>
```

I expect output like:
```
IntHyperParameter(min=0, max=10)
StringCatHyperParameter(options=['a', 'b', 'c'])
FloatExpHyperParameter(min=1e1, max=1e10)
```

**Comment by csala** [comment]
I agree on that the returns of `__repr__` are not right, but I disagree with the proposed output.

According to the [Python Data model documentation](https://docs.python.org/3/reference/datamodel.html#object.__repr__), the returns of the `__repr__` method should be, when possible, python code that when executed delivers an object as similar as possible as the one being represented.

So, in this case, I think that we should have something like:

```
>>> HyperParameter('string', ['a', 'b', 'c'])
StringHyperParameter(ParamType.STRING, ['a', 'b', 'c'])
```

Bear in mind that for an "informal or nicely printable string representation of an object" we should use the `__str__` method, so we could still have:

```
>>> hp = HyperParameter('string', ['a', 'b', 'c'])
>>> hp
StringHyperParameter(ParamType.STRING, ['a', 'b', 'c'])
>>> str(hp)
"StringHyperParameter(options=['a', 'b', 'c'])"
```

But I think this extra step is not really necessary.

**Comment by micahjsmith** [comment]
Fair enough, I agree to use `__str__` for the expected output above and to `__repr__` as you suggest.

**Comment by pvk-developer** [comment]
The new structure allows to implement a `__repr__` for each `HyperParameter` as @micahjsmith commented on the first place. I will implement this as part of #141
