### ISSUE TITLE
Simplify HyperParameter implementation

### ISSUE THREAD

**Issue by micahjsmith** [HDI-Project/BTB#123]
The use of `HyperParameter` as a class and metaclass has led to a fair amount of confusion. I suggest splitting out metaclass functionality into `HyperParameterMeta` (i.e. `__new__`). 

One consequence is that one can create some concrete hyperparameters directly, like `IntHyperParameter([0, 10])`. This would also simplify the hyperparameter repr (#121).

**Comment by pvk-developer** [comment]
Closing this issue as we have redesigned `HyperParameters` in #129
