### ISSUE TITLE
Fix example data ingest 

### ISSUE THREAD

**Issue by brucebcampbell** [HDI-Project/BTB#127]
fetch_mldata may need to be replaced with fetch_openml

* BTB version: 0.2.5
* Python version: 3.7
* Operating System:   Ubuntu 18.04.1 LTS

### Description
When trying to run some examples I ran into trouble with the MNIST download. It seems mldata.org has been down for quite a while and it's been replaced by openml.org. 

I think sklearn.datasets.fetch_openml is meant to replace the old API.

### What I Did

In running BTB\examples\random_forest.py
This is the code that is having trouble and a best guess at a fix
```
from sklearn.datasets import fetch_openml,fetch_mldata
#mnist = fetch_mldata('MNIST original')
mnist = fetch_openml('mnist_784')

```

**Comment by csala** [comment]
Closed via #128
