### ISSUE TITLE
Proposal: sunset python 2

### ISSUE THREAD

**Issue by micahjsmith** [HDI-Project/BTB#146]
Support for python 2.7 [officially ends on January 1 2020](https://pythonclock.org/). I propose that our first release after that date drops support for python 2

- delete the `bcyphers/futurize` branch
- modernize all code that is currently tied to python 2.7 compatibility

**Comment by pvk-developer** [comment]
After the following release: https://github.com/HDI-Project/BTB/releases/tag/v0.3.5
- Deleted `bcyphers/futurize` branch.
- Dependancies for `Python 2`, like `mock`, have been removed and part of the code reworked to be `Python 3`.
