### ISSUE TITLE
Spurious warning about not enough data

### ISSUE THREAD

**Issue by micahjsmith** [HDI-Project/BTB#18]
A warning [is raised](https://github.com/HDI-Project/BTB/blob/30cc8d1affea2b37771eb865b9df30dc9d0657e8/btb/tuning/gp.py#L43) by GP tuner when there is "not enough data": `WARNING:btb:GP: not enough data, falling back to uniform sampler`.
https://github.com/HDI-Project/BTB/blob/30cc8d1affea2b37771eb865b9df30dc9d0657e8/btb/tuning/gp.py#L43

A warning should be raised if the user can change something to subsequently avoid the issue. The change seems to be that the user, in their tuning loop, should create a `Uniform` tuner for two iterations and then switch to a `GP` tuner. But that is the fallback behavior in the `GP` routine anyway. So why not just remove the warning?

**Comment by csala** [comment]
I think that having the warning there is OK.

Otherwise, if r_mininum is pushed too high when the instance is created, the user could be actually using a Uniform tuner for all the process without even noticing it.

**Comment by kveerama** [comment]
I think a better log here would be ('Using uniform sampler as user specified r_minimum threshold is not met') and it need not be warning.
