### ISSUE TITLE
Publish on PyPI

### ISSUE THREAD

**Issue by micahjsmith** [HDI-Project/BTB#19]
We've only tagged a version 0.1 but I think it would be suitable to publish this package on PyPI given that ATM has it as a dependency and there are other external users. (Such as myself.)

For packaging purposes, one can take a look at [cookiecutter-pypackage](https://github.com/audreyr/cookiecutter-pypackage/tree/master/%7B%7Bcookiecutter.project_slug%7D%7D). It shouldn't be hard to adapt the config files in the template package root. Another nice thing would be to configure travis to publish to PyPI every time a new release is tagged. There are instructions in the cookiecutter root docs folder.

**Comment by csala** [comment]
Name `btb` is already taken on PyPi, so we need to find another project name for the publication.

Note that using a different name for PyPi does not necessarily force us to change the name of the packaging, so one should be able to do:

```
pip install the-name-yet-to-be-decided
python
>>> import btb
```

**Comment by csala** [comment]
baytune v0.1.1 and v0.1.2 already release.
