### ISSUE TITLE
We need tests!

### ISSUE THREAD

**Issue by bcyphers** [HDI-Project/BTB#2]
We need some basic unit and integration tests to make sure that changes to this repo don't break functionality. This is particularly necessary for upgrading to python 2/3. We'll eventually want to integrate with CircleCI and github so that we can evaluate pull requests from the web.

A list to start:
- Unit tests for each method in `tuner.py` and `selector.py`
- Test selectors with different kinds of input to make sure they make the right choices
- Test tuners with different kinds of input to make sure they don't break and make logical choices
- End-to-end tests with different `sklearn` classifiers to make sure hyperparameter typing is handled correctly

**Comment by csala** [comment]
Already in master
