### ISSUE TITLE
Docs not being served from gh-pages

### ISSUE THREAD

**Issue by micahjsmith** [HDI-Project/BTB#31]
The docs are not accessible from gh-pages. They should live at https://hdi-project.github.io/btb, but that link gives a 404 error. 

Debugging
- The repo seems to be correctly configured to serve from gh-pages branch, and the gh-pages branch has the expected source files.
- You can see that the site is structured correctly by using rawgit.com to serve the files: https://rawgit.com/HDI-Project/BTB/gh-pages/index.html.
- You can compare to fhub_core, which uses an identical configuration: https://hdi-project.github.io/btb (404 error) vs https://hdi-project.github.io/fhub_core (works correctly), and https://github.com/HDI-Project/BTB/tree/gh-pages vs https://github.com/HDI-Project/fhub_core/tree/gh-pages

**Comment by csala** [comment]
I could fix it following the advice from here: https://stackoverflow.com/questions/11577147/how-to-fix-page-404-on-github-page

I basically run locally:
```
git checkout gh-pages
git push origin --delete gh-pages
git push origin
```

**Comment by csala** [comment]
As an additional note, it looks like the URL is case sensitive.

So, the actual docs are here: https://hdi-project.github.io/BTB/
