### ISSUE TITLE
Make BTB compatible with python 2 and 3

### ISSUE THREAD

**Issue by bcyphers** [HDI-Project/BTB#4]
using http://python-future.org/automatic_conversion.html. #3 is a start, but we still need to deal with strings.

**Comment by csala** [comment]
Current code is already compatible with python 2.7, 3.4, 3.5 and 3.6, as they are all tested in the tox run.

However, there are some imports that seem to be unnecessary for the compatibility.

I tried to remove them in the branch `python2_3_compat` and all the tests succeed, so I would suggest merging the changes and then closing this issue.
