### ISSUE TITLE
Update HISTORY in advance of v0.2.0 release

### ISSUE THREAD

**Issue by micahjsmith** [HDI-Project/BTB#43]
As we prepare to release v0.2.0, let's update the HISTORY file with a description of the new features or changes that have been added since 0.1.0 was tagged. For refactoring, cleaning, and other internal changes, we can just say "other various improvements".

**Comment by csala** [comment]
What do you think about just listing the closed PRs?

Maybe for some of them just rephrase the title (f.e. "We need docs" -> "Update README with project description, installation instructions and usage examples")
