### ISSUE TITLE
Add code docstrings

### ISSUE THREAD

**Issue by csala** [HDI-Project/BTB#52]
Most of the code has very poor docstrings, if any at all.

It should be properly documented using a style supported by Sphinx, such as the [Google](https://numpydoc.readthedocs.io/en/latest/format.html) or [Numpy](https://numpydoc.readthedocs.io/en/latest/format.html) ones.

Including a docstring checker such as [pep257](https://pypi.org/project/pep257/0.5.0/), [pydocstyle](https://github.com/PyCQA/pydocstyle) or even [pylint](https://stackoverflow.com/questions/29597618/is-there-a-tool-to-lint-python-based-on-the-google-style-guide) would be a good option too.

Note that pydocstyle [supports the numpy style](https://stackoverflow.com/questions/42123798/is-there-any-way-to-lint-a-python-file-to-check-for-numpy-documentation-style-ad)

**Comment by micahjsmith** [comment]
+1

I personally prefer the Google style, with Sphinx support using `sphinx.ext.napoleon`.

I've never used a docstring checker so I have no preference, except pylint seems maybe a bit overpowered

**Comment by csala** [comment]
Bear in mind that `sphinx.ext.napoleon` also supports numpy!

Regarding the checker, pydocstyle can even be integrated with flake8: https://github.com/PyCQA/flake8-docstrings, so it looks like a good option to me.

What I don't know is how well pydocstyle works with Google Style docstrings.

**Comment by micahjsmith** [comment]
This can be closed when all public functions/classes have docstrings.

**Comment by pvk-developer** [comment]
After #131  and major update on code documentation and docstrings, I consider it as fixed.
