### ISSUE TITLE
Test for None in HyperParameter.cast instead of HyperParameter.__init__

### ISSUE THREAD

**Issue by csala** [HDI-Project/BTB#62]
https://github.com/HDI-Project/BTB/blob/28931f8a5dda5f5f3a05edbd08212d190fff7aea/btb/hyper_parameter.py#L63

Perhaps it would be a good idea to move this test for None values to the cast method itself.

So, here we do:

self.range = [self.cast(value) for value in param_range]
And in the cast methods we do:

def cast(self, value):
    if value is not None:  # else returns None implicitly
        return whatever
This would give each subclass the possibility to decide whether None values are acceptable or not.

**Comment by micahjsmith** [comment]
This is a reasonable idea, go ahead and submit a PR?
