### ISSUE TITLE
Question: Should we exclude tests in MANIFEST.in?

### ISSUE THREAD

**Issue by csala** [HDI-Project/BTB#65]
Current `MANIFEST.in` includes tests folder into the distribution archive:

```
recursive-include tests *
```

Is it needed?
Should this be an exclude instead?

**Comment by micahjsmith** [comment]
I think that it is customary to include tests, which are otherwise included by default. Consumers of the sdist might want to run the tests to confirm that installation worked properly on their system.

See https://docs.python.org/3.6/distutils/sourcedist.html#specifying-the-files-to-distribute
