### ISSUE TITLE
Fix/cleanup names

### ISSUE THREAD

**Issue by csala** [HDI-Project/BTB#69]
Some names should be fixed:

Proposed changes:
* `btb.tuning.tuner.BaseTuner` should be `btb.tuning.base.BaseTuner`
* `btb.selection.selector.Selector` should be `btb.selection.base.BaseSelector`
* `btb.recommendation.recommender.BaseRecommender` should be `btb.recommendation.base.BaseRecommender`

Also, the following module seem to have no real use, so I propose removing them:
* `btb.tuning.custom_tuner.CustomTuner`
* `btb.selection.custom_selector.CustomSelector`

**Comment by micahjsmith** [comment]
Additional proposed changes
- add appropriate suffixes to all tuner and selector classes (e.g. `GP` -> `GPTuner`, `Uniform` -> `UniformTuner` or `UniformSelector`)

**Comment by micahjsmith** [comment]
Custom tuners and selectors is used by https://github.com/HDI-Project/ATM/blob/master/atm/worker.py#L88 and https://github.com/HDI-Project/ATM/blob/master/atm/worker.py#L120. Should confirm that those blocks can be safely deleted.

**Comment by pvk-developer** [comment]
This issue has been fixed by the new version `0.3.0` and the following issues solve this one: #131  and #140
