### ISSUE TITLE
`ParamTypes.STRING` tunables do not work.

### ISSUE THREAD

**Issue by csala** [HDI-Project/BTB#74]
* BTB version: 0.2.0
* Python version: any
* Operating System: any

### Description

`ParamTypes.STRING` tunables do not work.

According to the stack trace, some value are expected to be numeric values but are strings.

### What I Did

```
>>> from btb import HyperParameter, ParamTypes
>>> from btb.tuning import GP
>>> tunables = [
...     ('a', HyperParameter(ParamTypes.STRING, ['a', 'b']))
... ]
>>> GP(tunables).propose()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xals/Projects/Pythia/MIT/BTB/btb/tuning/tuner.py", line 154, in propose
    candidate_params = self._create_candidates()
  File "/home/xals/Projects/Pythia/MIT/BTB/btb/tuning/tuner.py", line 110, in _create_candidates
    return self._random_candidates(n)
  File "/home/xals/Projects/Pythia/MIT/BTB/btb/tuning/tuner.py", line 83, in _random_candidates
    diff = hi - lo
TypeError: unsupported operand type(s) for -: 'str' and 'str'
```

**Comment by csala** [comment]
Also, when digging into it, `ParamTypes.INT_CAT` also do not work entirely as expected, even though they do not fail.

The problem is `btb/tuning/tuner.py` lines 79-84:
```
if param.is_integer:
    column = np.random.randint(lo, hi + 1, size=n)

 else:
    diff = hi - lo
    column = lo + diff * np.random.rand(n)

    candidates[:, i] = column
```

Since categorical HyperParameters are NOT integers, they fall into the `els`e branch and end up getting float values instead of integer ones.

**Comment by micahjsmith** [comment]
Good catch, I’d also think our basic test suite should be expanded if they had not previously caught stuff like this
