### ISSUE TITLE
The computation of avg_rewards in BestKReward

### ISSUE THREAD

**Issue by JuliaGast** [HDI-Project/BTB#89]
* BTB version: 0.2.2-dev
* Python version: 3.6.5
* Operating System: Ubuntu

### Description
 As far as I understand, to choose the next hyperpartition, the bandit
(class UCB1) is given a dict choice_rewards, with a list for each
possible choice. 
Based on this list, it computes an average reward (l.36 in ucb1.py) for
each choice, and this avg_reward together with an error term then
constitutes to the choice's score (l. 39).

This choice_rewards dict can be computed in the class BestKReward,
using the function compute_rewards.

Here you give a list with all so far reached scores [in my case
accuracies], the scores which are >= the k best elements are kept, and
all values smaller than those k best elements are set to zero.

If you would e.g. have a list with scores:
`s1 = [ 0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.7, 0.7, 0.8, 0.9]`
and you set `k = 3`, the function would return 
`cr1 = [ 0, 0, 0, 0, 0, 0, 0.7, 0.7, 0.8, 0.9]`
and thus the avg_reward1 would be computed to `0.31`.

Whereas, if for another hyperpartition you would e.g. have the list
with scores:
`s2 =  [ 0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.7, 0.7, 0.8, 0.8]`
and you again set `k = 3`, the function would return 
`cr2 = [ 0,  0.5, 0.5, 0.5, 0.5, 0.5, 0.7, 0.7, 0.8, 0.8]`
which would lead to an avg_reward2 of `0.55`,
where then 0.55 > 0.31,

although, actually, the first hyperpartition had a better result
regarding the accuracies, as it reached a higher value at its last
evaluation. This seems a little odd to me. 

This leads to my question: **Why do you take those values which have been
set to zero into account when computing the avg_reward?
Wouldn't it be better to e.g. set them to nan and not take them into account for the avg_reward?**

### What I Did

init
```
self.selector = BestKReward(algos, k)        
 ```

Run Selector from BTB library, which needs as input the scores (dict, keys: algorithm names, values: for each algorithm: so far reached accuracies for each evaluation )
```
next_algo = self.selector.select(self.scores_for_bandit)
```

The output was as expected the next algorithm to choose; problem see above

**Comment by micahjsmith** [comment]
I am looking into this and agree something is amiss.

1. I think exactly k scores should be set to nonzero, rather than all the scores matching k unique values. This suggests that the implementation of compute_rewards is buggy when the input contains non-unique scores.
2. I am unable to find a reference on the "Best K" algorithms so I don't know how zeros should be treated, but my intuition matches yours, @JuliaGast, that the zeros should not factor into the average reward computation.

**Comment by micahjsmith** [comment]
This degenerate case suggests point 1 above should be fixed:

```
def compute_rewards(scores, k):
    kth_best = sorted(scores, reverse=True)[k-1]
    return [s if s>= kth_best else 0. for s in scores]

scores = [0.1, 0.7, 0.7, 0.7, 0.8, 0.8]
k = 3
rewards = compute_rewards(scores, k)
np.mean(rewards)
# 0.6166666666666666

scores = [0.1, 0.69999999999, 0.7, 0.7, 0.8, 0.8]
k = 3
rewards = compute_rewards(scores, k)
np.mean(rewards)
# 0.5
```
