### ISSUE TITLE
Fix import statement in selection_example.py

### ISSUE THREAD

**Issue by wsnalice** [HDI-Project/BTB#90]
* BTB version: 0.2.2-dev
* Python version: Python 2.7.10
* Operating System: Mac

### Description

Import error occurred while running selection_example.py.
Problem: wrong file to import from

### What I Did

python selection_example.py

Traceback (most recent call last):
  File "selection_example.py", line 8, in <module>
    from btb.selection import Selector
ImportError: cannot import name Selector

**Comment by micahjsmith** [comment]
Closed by #91
