### ISSUE TITLE
Spurious SciKit-Learn Import

### ISSUE THREAD

**Issue by thswear** [HDI-Project/BTB#92]
* BTB version: 0.1.2
* Python version: 3.7.0
* Operating System: MacOS

### Description

There appears to be a spurious import on line 9 of `btb/tuning/gp.py` of BTB version 0.1.2. The script imports `GaussianProcess` from `sklearn.gaussian_process` which does not exists in the latest version of sci-kit learn (0.20.0) causing an error. The `GaussianProcess` import is not used in the subsequent code, so I think the fix is as simple as removing that import (leaving only the `GaussianProcessRegressor` import).

### What I Did

I installed ATM from scratch and got the following error when trying to test entering a data run:
```
$ python enter_data.py 
/Users/tss/codes/ATM/venv2/lib/python3.7/site-packages/scikit_learn-0.20.0-py3.7-macosx-10.13-x86_64.egg/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "enter_data.py", line 8, in <module>
    from atm.config import (add_arguments_aws_s3, add_arguments_sql,
  File "/Users/tss/codes/ATM/atm/config.py", line 12, in <module>
    from atm.constants import (BUDGET_TYPES, CUSTOM_CLASS_REGEX, DATA_TEST_PATH,
  File "/Users/tss/codes/ATM/atm/constants.py", line 11, in <module>
    from btb.tuning import GP, GPEi, GPEiVelocity
  File "/Users/tss/codes/ATM/venv2/lib/python3.7/site-packages/baytune-0.1.2-py3.7.egg/btb/tuning/__init__.py", line 5, in <module>
  File "/Users/tss/codes/ATM/venv2/lib/python3.7/site-packages/baytune-0.1.2-py3.7.egg/btb/tuning/gp.py", line 9, in <module>
ImportError: cannot import name 'GaussianProcess' from 'sklearn.gaussian_process' (/Users/tss/codes/ATM/venv2/lib/python3.7/site-packages/scikit_learn-0.20.0-py3.7-macosx-10.13-x86_64.egg/sklearn/gaussian_process/__init__.py)
```

I was able to download the BTB v0.1.2 code and remove `GaussianProcess` import. This seems to have fixed the issue in ATM as I could add a datarun to the ModelHub.

**Comment by micahjsmith** [comment]
Thanks for reporting. We'll try to release a v0.1.3 with this bugfix.

Ultimately, in https://github.com/HDI-Project/ATM/issues/112 we'd like to update BTB to v0.2 anyway and we should prioritize that upgrade given errors like these.
